force-app/main/default/objects/ExecRaySettings__c/ExecRaySettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for eXec-Ray app</description>
    <label>eXec-Ray Settings</label>
</CustomObject>

force-app/main/default/objects/ExecRaySettings__c/fields/UsePlatformCache__c.field-meta.xml
<CustomField>
    <fullName>UsePlatformCache__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Specify if you want to use Platform Cache in order to minimize loading time when there is a lot of Metadata in the org</description>
    <label>Use Platform Cache</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ExecutionTreeHandlerTest.cls
@IsTest
public with sharing class ExecutionTreeHandlerTest {
    @IsTest
    private static void test_getObjectList(){
        Test.startTest();
            ExecutionTreeHandler handler = new ExecutionTreeHandler();
            List<SFObject> sfObjects = handler.getObjectList();
        Test.stopTest();

        Map<String, SFObject> sfobjectsByLabel = new Map<String, SFObject>();
        for(SFObject sfobject : sfobjects){
            sfobjectsByLabel.put(sfobject.label, sfobject);
        }

        SFObject account = sfobjectsByLabel.get('Account');
        
        System.assertEquals('Account', account.apiName, 'Account not retrieved.');
        System.assertEquals('Standard', account.type, 'Incorrect account type defined.');        
        System.assertEquals('Account', account.apiName, 'Incorrect account type defined.');
    }

    @IsTest
    private static void test_getCategoryOperations(){
        CategoryOperation categoryOperation = new CategoryOperation();
        categoryOperation.category = 'Validation Rule';
        CategoryOperation.order = 1;
        List<CategoryOperation> categoryOperations = new List<CategoryOperation>();
        categoryOperations.add(categoryOperation);
        Map<String, List<CategoryOperation>> categortiesByObject = new Map<String, List<CategoryOperation>>();
        categortiesByObject.put('Account', categoryOperations);

        Test.startTest();
            MockUtil mock = new MockUtil(MetadataFetcher.class);
            ExecutionTreeHandler handler = new ExecutionTreeHandler();
            handler.testStubFetcher = (MetadataFetcher) mock.instance;
            mock.setReturnValue('requestMetadata', categortiesByObject);
            List<CategoryOperation> sfObjects = handler.getCategoryOperations('Account');
        Test.stopTest();

        System.assertEquals(4, sfObjects.size(), 'Wrong number of operations returned.');
    }

    @IsTest
    private static void test_getCategoryOperationsWithCache(){
        CategoryOperation categoryOperation = new CategoryOperation();
        categoryOperation.category = 'Validation Rule';
        CategoryOperation.order = 1;
        List<CategoryOperation> categoryOperations = new List<CategoryOperation>();
        categoryOperations.add(categoryOperation);
        Map<String, List<CategoryOperation>> categortiesByObject = new Map<String, List<CategoryOperation>>();
        categortiesByObject.put('Account', categoryOperations);

        Cache.OrgPartition orgPartition = Cache.Org.getPartition(PlatformCacheHelper.PARTITION_LABEL);
        orgPartition.put(PlatformCacheHelper.cacheType.categories, JSON.serialize(categortiesByObject), 1800); 

        ExecRaySettings__c execRaySettings = ExecRaySettings__c.getInstance();
        execRaySettings.UsePlatformCache__c = true;
        upsert execRaySettings;

        Test.startTest();
            MockUtil mock = new MockUtil(MetadataFetcher.class);
            ExecutionTreeHandler handler = new ExecutionTreeHandler();
            handler.testStubFetcher = (MetadataFetcher) mock.instance;
            mock.setReturnValue('requestMetadata', categortiesByObject);
            List<CategoryOperation> sfObjects = handler.getCategoryOperations('Account');
        Test.stopTest();

        System.assertEquals(1, sfObjects.size(), 'Wrong number of operations returned.');
    }

    @IsTest
    private static void test_getCachedOperations(){
        CategoryOperation categoryOperation = new CategoryOperation();
        categoryOperation.category = 'testOperation';
        categoryOperation.order = 1;

        Map<String, List<CategoryOperation>> operationsByObject = new Map<String, List<CategoryOperation>>(); 
        operationsByObject.put('Account0', new CategoryOperation[]{categoryOperation});

        Cache.OrgPartition orgPartition = Cache.Org.getPartition(PlatformCacheHelper.PARTITION_LABEL);
        orgPartition.put(PlatformCacheHelper.cacheType.categories, JSON.serialize(operationsByObject), 1800); 

        Test.startTest();
            ExecutionTreeHandler handler = new ExecutionTreeHandler();
            Map<String, List<CategoryOperation>> sfObjects = handler.getCachedOperations();
        Test.stopTest();

        System.assertNotEquals(null, orgPartition.get(PlatformCacheHelper.cacheType.categories), 'Cache is empty');
        System.assertEquals(JSON.serialize(operationsByObject), JSON.serialize(sfObjects), 'Wrong data returned by the cache.');
    }
}